; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = teensy
board = teensy41
upload_protocol = teensy-gui
framework = arduino
lib_deps = 
	sparkfun/SparkFun u-blox GNSS v3
	https://github.com/greiman/SdFat.git#2.3.1
	https://github.com/RobTillaart/MS5611.git
		https://github.com/redstonee/bmi088-arduino-esp32.git


build_flags = 
	-Wno-unknown-pragmas -Wall -Wextra  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -DARM_MATH_CM7 -DARM_MATH_MATRIX_CHECK
	-std=gnu++17
lib_compat_mode = strict

[env:debug]
build_flags = 
	${env.build_flags} -D DEBUG -g3 -O0 -D HITL
lib_deps = 
	${env.lib_deps}


[env:release]
build_flags = 
	${env.build_flags} -O3